_wandb:
    value:
        cli_version: 0.25.0
        e:
            4jasec108oud4e0cf4vfrzrvcqho9hpk:
                args:
                    - train
                    - spacy_uzbek/configs/config_transformer.cfg
                    - --output
                    - saved_models/spacy/transformer_uzudt
                    - --paths.train
                    - spacy_uzbek/data/uz_uzudt.train.spacy
                    - --paths.dev
                    - spacy_uzbek/data/uz_uzudt.dev.spacy
                    - --training.logger.run_name
                    - transformer_uzudt
                    - --gpu-id
                    - "0"
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "783639638016"
                        used: "493445595136"
                email: s.matlatipov@nuu.uz
                executable: C:\Users\User\code\robust-parsing-uzbek\.venv\Scripts\python.exe
                git:
                    commit: a0bf59a6a9867ecd223043c318d41040bca33b4c
                    remote: https://github.com/SanatbekMatlatipov/robust-parsing-uzbek.git
                gpu: NVIDIA RTX A6000
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX A6000
                      uuid: GPU-029e78fc-9141-1f23-dff3-45af218bd463
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX A6000
                      uuid: GPU-4ad88ff7-2389-99c0-2e44-0c2e3d5019cc
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX A6000
                      uuid: GPU-99d05cf1-1d7c-b6ed-17e6-12f3d2ef77ef
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX A6000
                      uuid: GPU-897832ed-6928-6e4f-fa7e-e8380a262537
                host: DT-BIZON-W11
                memory:
                    total: "549584429056"
                os: Windows-10-10.0.26200-SP0
                program: -m spacy.__main__
                python: CPython 3.11.9
                root: C:\Users\User\code\robust-parsing-uzbek
                startedAt: "2026-03-01T07:52:12.291821Z"
                writerId: 4jasec108oud4e0cf4vfrzrvcqho9hpk
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 11
                - 33
                - 49
            "2":
                - 1
                - 11
                - 33
                - 49
            "3":
                - 2
                - 16
                - 17
            "4": 3.11.9
            "5": 0.25.0
            "6": 4.49.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.25.0
            "13": windows-amd64
components:
    value:
        morphologizer:
            extend: false
            factory: morphologizer
            label_smoothing: 0
            model:
                '@architectures': spacy.Tagger.v2
                "no": null
                normalize: false
                tok2vec:
                    '@architectures': spacy-transformers.TransformerListener.v1
                    grad_factor: 1
                    pooling:
                        '@layers': reduce_mean.v1
                    upstream: transformer
            overwrite: true
            scorer:
                '@scorers': spacy.morphologizer_scorer.v1
        parser:
            factory: parser
            learn_tokens: false
            min_action_freq: 30
            model:
                '@architectures': spacy.TransitionBasedParser.v2
                extra_state_tokens: false
                hidden_width: 128
                maxout_pieces: 3
                "no": null
                state_type: parser
                tok2vec:
                    '@architectures': spacy-transformers.TransformerListener.v1
                    grad_factor: 1
                    pooling:
                        '@layers': reduce_mean.v1
                    upstream: transformer
                use_upper: true
            moves: null
            scorer:
                '@scorers': spacy.parser_scorer.v1
            update_with_oracle_cut_size: 100
        tagger:
            factory: tagger
            label_smoothing: 0
            model:
                '@architectures': spacy.Tagger.v2
                "no": null
                normalize: false
                tok2vec:
                    '@architectures': spacy-transformers.TransformerListener.v1
                    grad_factor: 1
                    pooling:
                        '@layers': reduce_mean.v1
                    upstream: transformer
            neg_prefix: '!'
            overwrite: false
            scorer:
                '@scorers': spacy.tagger_scorer.v1
        transformer:
            factory: transformer
            max_batch_items: 4096
            model:
                '@architectures': spacy-transformers.TransformerModel.v3
                get_spans:
                    '@span_getters': spacy-transformers.strided_spans.v1
                    stride: 96
                    window: 128
                mixed_precision: false
                name: tahrirchi/tahrirchi-bert-base
                tokenizer_config:
                    use_fast: true
            set_extra_annotations:
                '@annotation_setters': spacy-transformers.null_annotation_setter.v1
corpora:
    value:
        dev:
            '@readers': spacy.Corpus.v1
            augmenter: null
            gold_preproc: false
            limit: 0
            max_length: 0
            path: spacy_uzbek/data/uz_uzudt.dev.spacy
        train:
            '@readers': spacy.Corpus.v1
            augmenter: null
            gold_preproc: false
            limit: 0
            max_length: 2000
            path: spacy_uzbek/data/uz_uzudt.train.spacy
initialize:
    value:
        after_init: null
        before_init: null
        init_tok2vec: null
        lookups: null
        vectors: null
        vocab_data: null
nlp:
    value:
        after_creation: null
        after_pipeline_creation: null
        batch_size: 128
        before_creation: null
        disabled: []
        lang: uz
        pipeline:
            - transformer
            - tagger
            - morphologizer
            - parser
        tokenizer:
            '@tokenizers': spacy.Tokenizer.v1
        vectors:
            '@vectors': spacy.Vectors.v1
paths:
    value:
        dev: spacy_uzbek/data/uz_uzudt.dev.spacy
        init_tok2vec: null
        train: spacy_uzbek/data/uz_uzudt.train.spacy
        vectors: null
system:
    value:
        gpu_allocator: pytorch
        seed: 42
training:
    value:
        accumulate_gradient: 3
        annotating_components: []
        batcher:
            '@batchers': spacy.batch_by_words.v1
            discard_oversize: false
            get_length: null
            size:
                '@schedules': compounding.v1
                compound: 1.001
                start: 100
                stop: 1000
                t: 0
            tolerance: 0.2
        before_to_disk: null
        before_update: null
        dev_corpus: corpora.dev
        dropout: 0.1
        eval_frequency: 200
        frozen_components: []
        gpu_allocator: pytorch
        logger:
            '@loggers': spacy.WandbLogger.v3
            entity: null
            log_dataset_dir: spacy_uzbek/data
            model_log_interval: null
            project_name: spacy-uzbek
            remove_config_values: []
            run_name: transformer_uzudt
        max_epochs: 0
        max_steps: 20000
        optimizer:
            '@optimizers': Adam.v1
            beta1: 0.9
            beta2: 0.999
            eps: 1e-08
            grad_clip: 1
            l2: 0.01
            l2_is_weight_decay: true
            learn_rate:
                '@schedules': warmup_linear.v1
                initial_rate: 5e-05
                total_steps: 20000
                warmup_steps: 250
            use_averages: false
        patience: 1600
        score_weights:
            dep_las: 0.25
            dep_las_per_type: null
            dep_uas: 0.25
            morph_acc: 0.1
            morph_per_feat: null
            pos_acc: 0.15
            sents_f: 0.1
            sents_p: null
            sents_r: null
            tag_acc: 0.15
            tag_micro_f: null
            tag_micro_p: null
            tag_micro_r: null
        seed: 42
        train_corpus: corpora.train
